### ISSUE TITLE
Figure out what's wrong with source-map electron builder issues

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1801]
## The Issue
When I upgraded Electron builder, I could not build locally on windows due to the below error. It would build on Travis fine (built on Linux). Mac worked also. 

Turns out the deb has the same issue as the local windows build. This is the most immediate fix we need. 

Also ran into this on Mac build when fixing the duplicate daemon downloads (http://build.lbry.io/app/build-2815_commit-bf8b843/)

```
     A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'source-map-support/source-map-support.js'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/opt/LBRY/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/LBRY/resources/app.asar/main.js:1:156)
    at Object.<anonymous> (/opt/LBRY/resources/app.asar/main.js:4:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

```

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kodxana** [comment]
Compile node_modules and put them in app.asar will fix this problem :)

**Comment by tzarebczan** [comment]
This was fixed by https://github.com/lbryio/lbry-desktop/pull/1803. Turned out to be an issue with the daemon not downloading on Linux(weird, since this worked before electron-builder changes) and locally on Windows. The build process was changed to download the daemon correctly in all cases.
