### ISSUE TITLE
Outstanding 0.30 release issues

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2345]
## The Issue
- [x] updater fails when clicking "use it now" - looks like it's not finding the updater file? The directory changed where the updater downloads. It works fine from 0.29.4 to 0.30 on Windows. Works fine on quit. Mac worked fine on rc1-rc2/3. https://github.com/electron-userland/electron-builder/issues/3526#issuecomment-473727934
```[18:59:01.218] [info] Found version 0.29.5-rc.3 (url: LBRY_0.29.5-rc.3.exe)
[18:59:01.219] [info] Downloading update from LBRY_0.29.5-rc.3.exe
[18:59:01.233] [debug] updater cache dir: C:\Users\thoma\AppData\Local\lbry-updater
[18:59:01.712] [info] Update has already been downloaded to C:\Users\thoma\AppData\Local\lbry-updater\pending\LBRY_0.29.5-rc.3.exe).
Install on explicit quitAndInstall
Error: Error: No valid update available, can't quit and install
    at g.NsisUpdater.install (c:\Program Files\LBRY\resources\app.asar\main.js:90:36262)
    at g.NsisUpdater.quitAndInstall (c:\Program Files\LBRY\resources\app.asar\main.js:90:35690)
    at EventEmitter.<anonymous> (c:\Program Files\LBRY\resources\app.asar\main.js:321:2975687)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (c:\Program Files\LBRY\resources\electron.asar\browser\api\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
Install on explicit quitAndInstall
Error: Error: No valid update available, can't quit and install
    at g.NsisUpdater.install (c:\Program Files\LBRY\resources\app.asar\main.js:90:36262)
    at g.NsisUpdater.quitAndInstall (c:\Program Files\LBRY\resources\app.asar\main.js:90:35690)
    at EventEmitter.<anonymous> (c:\Program Files\LBRY\resources\app.asar\main.js:321:2975687)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (c:\Program Files\LBRY\resources\electron.asar\browser\api\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
```

- [x] subscribe button showing on anonymous channels
- [x] search page shows 0 files for results/direct channel (search @NorVegan)
- [x] need to click back twice sometimes after accessing channel from search page (try @jiggytom search)
- [ ] mouse forward/back navigation lost for Windows. This version of electron was supposed to make it native for Linux. Looks like it's not being triggered with window.on(app-command)...
- [x] 3d models don't show
- [x] doc/pdf viewer broken (lbry://@mime#649f5d766f6ca2db1be249b09e164ffe52939751)
- [x] move daemon directory back to static/daemon - otherwise all windows users will get a new firewall prompt.
- [ ] volume control not working in media player
  - Not working with electron@4.1.0
  - https://productforums.google.com/forum/#!topic/chrome/2lN8hckg9cg
- [x] lost blue balance background on wallet overview
- [x] sandbox in use when opening open.lbry.io hyperlinks (when app running) 
![image](https://user-images.githubusercontent.com/8120721/54498681-96b79a80-48e0-11e9-84c0-1123352accfa.png)
- [x] video pauses on waiting for metadata
- [x] taskbar icon quality seems work on Windows

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by skhameneh** [comment]
Working on 3D rendering

**Comment by seanyesmunt** [comment]
Working on fixing PDF's. Looks like it was broken in 0.3
https://github.com/electron/electron/issues/12337

**Comment by seanyesmunt** [comment]
Gave up on the PDF viewer and fixed a bunch of other issues.

**Comment by seanyesmunt** [comment]
Starting back up on the pdf viewer. I think it's just that and the 3d viewer

**Comment by skhameneh** [comment]
3D models should be working in full

**Comment by tzarebczan** [comment]
The mouse forward / back is an issue in electron https://github.com/electron/electron/issues/17134
