### ISSUE TITLE
Current app crashes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2497]
## The Issue
1) I got this to happen once after publishing to a channel and then searching for that channel. Might be related to navigation/search. 
```
Desktop Error: /Applications/LBRY.app/Contents/Resources/app.asar/index.html

   TypeError: Cannot read property 'toLowerCase' of undefined
   at t.forEach.e (file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:52236)
   at Array.forEach (<anonymous>)
   at a.createSelector (file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:51991)
   at file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:114815
   at file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:114245
   at file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:114945
   at file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:114245
   at Function.t.a.Object [as mapToProps] (file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:200:217284)
   at r (file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:60017)
   at Function.r.mapToProps (file:///Applications/LBRY.app/Contents/Resources/app.asar/ui.js:1:60153)
```

2) Happens on a claim like detailsJson that was manually crafted without a title. 
```
Desktop Error: /C:/Program%20Files/LBRY/resources/app.asar/index.html

   TypeError: Cannot read property 'replace' of undefined
   at a.createSelector (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:22811)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114815
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114245
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114945
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114245
   at Function.t.a.Object [as mapToProps] (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:200:303370)
   at r (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60017)
   at Function.r.mapToProps (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60153)
   at r (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60017)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:61353
User(824249) Desktop Error: /C:/Program%20Files/LBRY/resources/app.asar/index.html

   TypeError: Cannot read property 'replace' of undefined
   at a.createSelector (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:22811)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114815
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114245
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114945
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114245
   at Function.t.a.Object [as mapToProps] (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:200:303370)
   at r (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60017)
   at Function.r.mapToProps (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60153)
   at r (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60017)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:61353
```

3) Possibly happens after accessing a channel right after an update (via SDK)
```
User(915443) Desktop Error: /C:/Program%20Files/LBRY/resources/app.asar/index.html

   TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
   at t.sortFunctions.(anonymous function).forEach.e (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:200:129430)
   at Array.forEach (<anonymous>)
   at c.render (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:200:129358)
   at Po (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:269:63001)
   at To (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:269:62796)
   at Io (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:269:66630)
   at qi (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:269:90674)
   at $i (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:269:91058)
   at Pl (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:269:97945)
   at Sl (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:269:97325)
```

4) not sure about this one, user was on 0.32.1
```
Desktop Error: /C:/Program%20Files/LBRY/resources/app.asar/index.html

   Error: URI does not include name.
   at je (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:17199)
   at Ze.a.createSelector (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:21540)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114815
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114245
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114945
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:114245
   at Function.Object [as mapToProps] (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:200:280567)
   at r (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60017)
   at Function.r.mapToProps (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60153)
   at r (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:60017)
```

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
I don't think these are workable without the URLs or steps to recreate the issues.
