### ISSUE TITLE
LBRY terminates unexpectedly on Linux systems due to uncaught exception

### ISSUE THREAD

**Issue by TrevtheForthDev** [lbryio/lbry-desktop#2575]
## The Issue
``` 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/trev/Downloads/pizza/opt/LBRY/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/home/trev/Downloads/pizza/opt/LBRY/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Trace/breakpoint trap
 ```

### Steps to Reproduce

1. Download .deb 2. run  3. mightthrowerror, reproducing really seems to be dependent on your system. Would suggest NixOS with an FHS compliant shell for reproducing

### Expected Behavior

Tell us what should happen.
Program should start
### Actual Behavior
Program doesn't start

### Tell us what happens instead.

Program terminated

### Suggested Solutions
Don't terminate. Jokes aside, perhaps a native app could be better here.

## System Configuration

- system: `"x86_64-linux"`
 - host os: `Linux 5.1.14, NixOS, 19.03.172968.3ddd23719bb (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(trev): `""`
 - channels(root): `"nixos-19.03.172979.8634c3b6199, nixos-hardware, unstable-19.09pre177651.aeb464dfd37"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

- LBRY Daemon version: No clue
- LBRY App version: Latest(No clue)
- LBRY Installation ID: (no clue)
- Operating system: NixOS (Non FHS compliant Linux Distro)

**Comment by tzarebczan** [comment]
hey @TrevtheForthDev , thanks for reaching out and sorry about the trouble. I think it's because you're missing gnome-keyring, which is required for the app at the moment. We plan to replace this with a regular cookie in a couple months. See https://github.com/lbryio/lbry-desktop/issues/386

**Comment by tzarebczan** [comment]
Let us know if that helps, but if you can't install gnome-keyring, maybe check out https://beta.lbry.tv in the meantime.
