### ISSUE TITLE
Random getBoundingClientRect errors when navigating

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2732]
Breaking out this error from https://github.com/lbryio/lbry-desktop/issues/2650
At the the time, I was navigating between claims on a channel page. I was on one claim, went back, then went to the first claim, which resulted in a green error screen.
```
app version: 0.35.0-rc.1
sdk version: 0.39.0
page: #/3-lofi-hip-hop-mix/26d2b24d988d8a66fe75cdf2de55501d2952b483
TypeError: Cannot read property 'getBoundingClientRect' of undefined
   at Object.i [as observe] (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:22:12054)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:22:13301
   at ho (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:75351)
   at Ho (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:82313)
   at Wo (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:85062)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:98269
   at Object.t.unstable_runWithPriority (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:248:3218)
   at Is (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:98204)
   at As (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:97980)
   at js (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:97325)```

**Comment by tzarebczan** [comment]
on beta.lbry.tv:  Try selecting channel text with your cursor - throws error

**Comment by tzarebczan** [comment]
This normally happens after you run into the bug where you see multiple channel previews. 

The "refreshing this app" button doesn't work - have to ctlr-R the app.
