### ISSUE TITLE
Error when trying to share unconfirmed publish/channel (also random for published content)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2874]
If you go into a recently published file/channel via the wallet page (clicking on url), and then try to share that link, the app errors. We should disable the page/hide buttons if it's still pending, or maybe prevent clicking it from the wallet page to begin with. Another option is just to support the case where canonical is not available for the share button. 

```TypeError: Cannot read property 'split' of undefined
   at u.render (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:195:266527)
   at Oa (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:63001)
   at ja (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:62796)
   at La (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:66630)
   at Yo (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:90674)
   at $o (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:91058)
   at As (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:97945)
   at js (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:97325)
   at Ds (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:98700)
   at xn (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:30568)
```

**Comment by tzarebczan** [comment]
Happens on already confirmed content too. Maybe it had cached the full url before it was confirmed. 
```Desktop Error: Uncaught error
app version: 0.35.3
sdk version: 0.40.1
page: #/@MacroLauncher:9
TypeError: Cannot read property 'split' of undefined
   at u.render (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:195:266527)```

**Comment by tzarebczan** [comment]
This was fixed in the last release.
