### ISSUE TITLE
Current lbry.tv/app crashes: Cannot set property 'selectedIndex' of null / remove child / owner document

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3370]
This is one of the most common failures we see on lbry.tv. My guess was something with the channel selector since it happens on claim and channel pages. 
```
User(xxxxx) Desktop Error: Uncaught error
lbry.tv
page: /@RebounD11:4/Ninja_si_idioti:9
TypeError: Cannot set property 'selectedIndex' of null
   at https://lbry.tv/public/ui.js:92:127104
   at https://lbry.tv/public/ui.js:92:2598
   at Array.forEach (<anonymous>)
   at m (https://lbry.tv/public/ui.js:92:2571)
   at o.i.setDefaults (https://lbry.tv/public/ui.js:92:127012)
   at new o (https://lbry.tv/public/ui.js:92:123005)
   at i.n.addChild (https://lbry.tv/public/ui.js:92:18188)
   at https://lbry.tv/public/ui.js:92:19585
   at Array.forEach (<anonymous>)
   at i.n.initChildren (https://lbry.tv/public/ui.js:92:19444)```

**Comment by tzarebczan** [comment]
also seeing ```Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.```

**Comment by tzarebczan** [comment]
This is one of the most common crashes but we don't know exactly why it's not happening.

**Comment by tzarebczan** [comment]
Another is ```User(2089056) Desktop Error: Uncaught error
lbry.tv
page: /?_ga=2.97246871.943126229.1577470773-1011802357.1577470773
TypeError: Cannot read property 'ownerDocument' of null
   at https://lbry.tv/public/ui.js:146:7198
   at c (https://lbry.tv/public/ui.js:146:7371)
   at Object.offset (https://lbry.tv/public/ui.js:146:10260)
   at e.exports (https://lbry.tv/public/ui.js:146:5135)
   at n.value (https://lbry.tv/public/ui.js:67:32498)
   at n.value (https://lbry.tv/public/ui.js:67:32080)
   at Va (https://lbry.tv/public/ui.js:137:82646)
   at Ga (https://lbry.tv/public/ui.js:137:85222)
   at https://lbry.tv/public/ui.js:137:98426
   at Object.t.unstable_runWithPriority (https://lbry.tv/public/ui.js:146:3468)```

**Comment by tzarebczan** [comment]
Haven't seen this crash in a while.
