### ISSUE TITLE
App crashes upon navigation to deleted text file

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#4038]
**Bug**

I'm in the habit of deleting all my LBRY downloads but keeping the blobs. In the latest app (0.45.0), if I navigate to one of these files (e.g., one of the `.py` files or `.md` files on my channel), it crashes (to the screen that tells you to refresh the app). In previous versions it showed a weird gray box.

Once the file has been re-created, the app displays the files correctly and does not crash.

**Comment by tzarebczan** [comment]
Thanks for spotting this issue. I think we've seen some crashes recently around this in our logs. 

```TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
   at Object.open (fs.js:406:3)
   at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:179:31)
   at ReadStream.open (internal/fs/streams.js:110:12)
   at new ReadStream (internal/fs/streams.js:99:10)
   at Object.createReadStream (fs.js:1706:10)
   at Object.file (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:195:200840)
   at n.r.componentDidMount (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:195:211513)
   at as (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:280:83399)
   at pl (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:280:101223)
   at t.unstable_runWithPriority (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:288:3844)
   at Hi (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:280:45072)
   at hl (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:280:97695)
   at Js (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:280:93900)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:280:45363
   at t.unstable_runWithPriority (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:288:3844)
   at Hi (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:280:45072)
```
