### ISSUE TITLE
lbry.tv embed third-party cookie security issue

### ISSUE THREAD

**Issue by chron0** [lbryio/lbry-desktop#4121]
**Bug**
When trying to use lbry.tv embed via iframe the content isnt loaded and fails in chromium with a security exception:

```
DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at https://lbry.tv/public/ui.js:39:149866
    at os (https://lbry.tv/public/ui.js:153:83404)
    at yl (https://lbry.tv/public/ui.js:153:102430)
    at t.unstable_runWithPriority (https://lbry.tv/public/ui.js:161:4072)
    at zi (https://lbry.tv/public/ui.js:153:45271)
    at vl (https://lbry.tv/public/ui.js:153:102189)
    at tl (https://lbry.tv/public/ui.js:153:93792)
    at https://lbry.tv/public/ui.js:153:45562
    at t.unstable_runWithPriority (https://lbry.tv/public/ui.js:161:4072)
    at zi (https://lbry.tv/public/ui.js:153:45271)
    at Ki (https://lbry.tv/public/ui.js:153:45507)
    at qi (https://lbry.tv/public/ui.js:153:45442)
    at Xs (https://lbry.tv/public/ui.js:153:90654)
    at Object.enqueueSetState (https://lbry.tv/public/ui.js:153:49227)
    at t.E.setState (https://lbry.tv/public/ui.js:122:1523)
    at https://lbry.tv/public/ui.js:94:18580
```
**To Reproduce**

Manually adding lbry.tv to third party cookie exceptions in chromium security settings seems to solve the issue, but that can't be considered a real solution...

**Expected behavior**
lbry embedding works without having to manually add a security exception.

**Screenshots**

![lbry-embed-fail](https://user-images.githubusercontent.com/3270028/80923395-056ce700-8d73-11ea-84ac-4070abcca12b.png)

**Additional context**

Am I doing it wrong and am really missing something here in terms of CORS or other settings I can fix on server side or could this be a bug?

**Comment by tzarebczan** [comment]
Thanks for filing, it's a duplicate of https://github.com/lbryio/lbry-desktop/issues/4017

Sounds like Brave and maybe other browsers block some additional things on embed.  If you turn shields off in brave, it works.

**Comment by chron0** [comment]
ah, i searched in issues for cookie only, not localstorage... sorry for dup
