### ISSUE TITLE
publish page crashes 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4800]
reported by a few users and seeing in crash logs 
```
app version: 0.48.0
sdk version: 0.81.0
page:
TypeError: Cannot read property 'media_type' of undefined
   at t.a (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:215:373678)
   at Ya (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:57961)
   at Ro (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:66822)
   at gs (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:105364)
   at cl (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:96695)
   at sl (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:96620)
   at Js (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:93701)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:45363
   at t.unstable_runWithPriority (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:307:3844)
   at Hi (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:45072)
   at qi (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:45308)
   at Gi (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:45243)
   at Ks (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:90486)
   at Object.enqueueSetState (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:299:49028)
   at t._.setState (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:238:1297)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:104940
```

```
app version: 0.48.0
sdk version: 0.81.0
page:
Error: URL does not include name.
   at H (file:///opt/LBRY/resources/app.asar/ui.js:1:30846)
   at G (file:///opt/LBRY/resources/app.asar/ui.js:1:33209)
   at a.createSelector (file:///opt/LBRY/resources/app.asar/ui.js:1:92491)
   at file:///opt/LBRY/resources/app.asar/ui.js:1:181906
   at file:///opt/LBRY/resources/app.asar/ui.js:1:181329
   at file:///opt/LBRY/resources/app.asar/ui.js:1:182037
   at file:///opt/LBRY/resources/app.asar/ui.js:1:181329
   at Function.Object.resolveUri [as mapToProps] (file:///opt/LBRY/resources/app.asar/ui.js:21:69015)
   at r (file:///opt/LBRY/resources/app.asar/ui.js:1:109328)
   at Function.r.mapToProps (file:///opt/LBRY/resources/app.asar/ui.js:1:109464)
   at r (file:///opt/LBRY/resources/app.asar/ui.js:1:109328)
   at file:///opt/LBRY/resources/app.asar/ui.js:1:110670
   at i.r.selectDerivedProps (file:///opt/LBRY/resources/app.asar/ui.js:1:107230)
   at i.s.renderWrappedComponent (file:///opt/LBRY/resources/app.asar/ui.js:1:108089)
   at i.s.indirectRenderWrappedComponent (file:///opt/LBRY/resources/app.asar/ui.js:1:107678)
   at gs (file:///opt/LBRY/resources/app.asar/ui.js:299:107559)
```

See: 
https://lbryians.slack.com/archives/CGSG94YEB/p1601320220201100 https://lbryians.slack.com/archives/CGSG94YEB/p1601297836182100

**Comment by kauffj** [comment]
@tzarebczan to find better repro and reassign

**Comment by tzarebczan** [comment]
This should fix it: https://github.com/lbryio/lbry-desktop/commit/19664726d6af350f6d787e6d8759228179c65030
