### ISSUE TITLE
0.48.1 and 0.48.2 not loading New (or Trending) videos from follows

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#4922]
just upgraded to 0.48.2 and am still getting the same issue with followed channels not loading after several attempts switching between "Top" and "New":
![Screenshot_2020-10-20_07-24-48](https://user-images.githubusercontent.com/773959/96579979-9d20ac00-12a5-11eb-894a-da0b42ad604e.png)

switching back to 0.48.0 for now because this issue doesn't happen here.

**Comment by tzarebczan** [comment]
Can you try it again - many times this is a temporary hiccup and will work after a couple retries. I don't think anything changed there between those versions. Let me know!

**Comment by aveekbh** [comment]
I see the same issue. New (or trending) from "following" list show this error, but top from "following" works.
I use the AppImage on Linux - this is the error trace I see when this issue occurs.

```
Daemon: 2020-10-21 23:55:02,535 ERROR    lbry.extras.daemon.daemon:708: error handling api request
Traceback (most recent call last):
  File "lbry/extras/daemon/daemon.py", line 700, in _process_rpc_call
  File "lbry/extras/daemon/daemon.py", line 2454, in jsonrpc_claim_search
  File "lbry/wallet/ledger.py", line 958, in claim_search
  File "lbry/wallet/ledger.py", line 848, in _inflate_outputs
  File "lbry/wallet/network.py", line 85, in send_request
  File "lbry/wallet/network.py", line 75, in send_request
  File "lbry/wallet/rpc/session.py", line 483, in send_request
lbry.wallet.rpc.jsonrpc.RPCError: (-32000, 'sqlite query timed out')
```

**Comment by Tcll** [comment]
Verified, same here:
```
Daemon: 2020-10-22 11:51:26,658 ERROR    lbry.extras.daemon.daemon:708: error handling api request
Traceback (most recent call last):
  File "lbry/extras/daemon/daemon.py", line 700, in _process_rpc_call
  File "lbry/extras/daemon/daemon.py", line 2454, in jsonrpc_claim_search
  File "lbry/wallet/ledger.py", line 958, in claim_search
  File "lbry/wallet/ledger.py", line 848, in _inflate_outputs
  File "lbry/wallet/network.py", line 85, in send_request
  File "lbry/wallet/network.py", line 75, in send_request
  File "lbry/wallet/rpc/session.py", line 483, in send_request
lbry.wallet.rpc.jsonrpc.RPCError: (-32000, 'sqlite query timed out')
```
not sure why I never thought to look in the terminal to catch that x.x

**Comment by tzarebczan** [comment]
This should be fixed in the latest RC: https://discordapp.com/channels/362322208485277697/377895389992321064/773568397064667146

**Comment by aveekbh** [comment]
> This should be fixed in the latest RC: https://github.com/lbryio/lbry-desktop/releases/tag/v0.49.0-rc.1

Verified, issue does not occur with v0.49.0-rc.1.
