### ISSUE TITLE
Fix console spam in dev

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6989]
It's annoying when you are trying to capture debug output, but seeing these errors in between.  
Filtering out Errors via DevTools is an option, but we'll mask any new/actual errors.

## List
- [ ] Sidebar

    <details>
      <summary>Toggle...</summary>

    ```
    Warning: React does not recognize the `pinnedUrls` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pinnedurls` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by LinkAnchor)
    in LinkAnchor (created by Context.Consumer)
    in Link (created by Context.Consumer)
    in NavLink (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in Connect(Component) (created by ForwardRef)
    in ForwardRef (created by SideNavigation)
    in li (created by SideNavigation)
    in ul (created by SideNavigation)
    in div (created by SideNavigation)
    in nav (created by SideNavigation)
    in div (created by SideNavigation)
    in SideNavigation (created by Context.Consumer)
    in Connect(SideNavigation) (created by Page)
    in div (created by Page)
    in Page (created by Context.Consumer)
    in Connect(Page) (created by ChannelsFollowingPage)
    in ChannelsFollowingPage (created by Context.Consumer)
    in Connect(ChannelsFollowingPage) (created by Context.Consumer)
    in Route (created by PrivateRoute)
    in PrivateRoute (created by AppRouter)
    in Switch (created by AppRouter)
    in Suspense (created by AppRouter)
    in AppRouter (created by Context.Consumer)
    in withRouter(AppRouter) (created by Context.Consumer)
    in Connect(withRouter(AppRouter)) (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in withRouter(App) (created by Context.Consumer)
    in Connect(withRouter(App)) (created by HotExportedConnect(withRouter(App)))
    in AppContainer (created by HotExportedConnect(withRouter(App)))
    in HotExportedConnect(withRouter(App)) (created by AppWrapper)
    in ErrorBoundary (created by Context.Consumer)
    in withRouter(ErrorBoundary) (created by AppWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext) (created by AppWrapper)
    in PersistGate (created by AppWrapper)
    in Provider (created by AppWrapper)
    in AppWrapper
     ```   
    </details>

- [ ] videojs localization
     <details>
      <summary>Toggle...</summary>

    ```
    instrument.ts:129 VIDEOJS: ERROR: TypeError: Cannot read property 'controlText' of undefined
    at t.z (videojs.jsx:319)
    at HTMLDivElement.r.dispatcher.r.dispatcher (video.es.js:2214)
    at sr (video.es.js:2350)
    at trigger (video.es.js:3291)
    at t.n.handleTechLoadStart_ (video.es.js:23075)
    at t.<anonymous> (video.es.js:22844)
    at HTMLVideoElement.r.dispatcher.r.dispatcher (video.es.js:2214)
    at HTMLVideoElement.r (helpers.ts:85)
    ```
    - An attempt to fix was previously submitted...
    </details>

- [ ] Notifications:  `<a>` cannot appear as a descendant of `<a>`.
     <details>
      <summary>Toggle...</summary>

    ```
    Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by LinkAnchor)
    in LinkAnchor (created by Context.Consumer)
    in Link (created by Context.Consumer)
    in NavLink (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in Connect(Component) (created by ForwardRef)
    in ForwardRef (created by UriIndicator)
    in UriIndicator (created by Context.Consumer)
    in Connect(UriIndicator) (created by Notification)
    in div (created by Notification)
    in a (created by LinkAnchor)
    in LinkAnchor (created by Context.Consumer)
    in Link (created by Context.Consumer)
    in NavLink
    in Unknown (created by Notification)
    in div (created by Notification)
    in Notification (created by Context.Consumer)
    in Connect(Notification) (created by NotificationsPage)
    in div (created by NotificationsPage)
    in div (created by NotificationsPage)
    in main (created by Page)
    in div (created by Page)
    in Page (created by Context.Consumer)
    in Connect(Page) (created by NotificationsPage)
    in NotificationsPage (created by Context.Consumer)
    in Connect(NotificationsPage) (created by Context.Consumer)
    in Route (created by PrivateRoute)
    in PrivateRoute (created by AppRouter)
    in Switch (created by AppRouter)
    in Suspense (created by AppRouter)
    in AppRouter (created by Context.Consumer)
    in withRouter(AppRouter) (created by Context.Consumer)
    in Connect(withRouter(AppRouter)) (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in withRouter(App) (created by Context.Consumer)
    in Connect(withRouter(App)) (created by HotExportedConnect(withRouter(App)))
    in AppContainer (created by HotExportedConnect(withRouter(App)))
    in HotExportedConnect(withRouter(App)) (created by AppWrapper)
    in ErrorBoundary (created by Context.Consumer)
    in withRouter(ErrorBoundary) (created by AppWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext) (created by AppWrapper)
    in PersistGate (created by AppWrapper)
    in Provider (created by AppWrapper)
    in AppWrapper
    ```
    </details>

- [ ] Notifications:  missing 'key'
     <details>
      <summary>Toggle...</summary>

    ```
    Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div (created by Notification)
    in div (created by Notification)
    in div (created by Notification)
    in div (created by Notification)
    in a (created by LinkAnchor)
    in LinkAnchor (created by Context.Consumer)
    in Link (created by Context.Consumer)
    in NavLink
    in Unknown (created by Notification)
    in div (created by Notification)
    in Notification (created by Context.Consumer)
    in Connect(Notification) (created by NotificationsPage)
    in div (created by NotificationsPage)
    in div (created by NotificationsPage)
    in main (created by Page)
    in div (created by Page)
    in Page (created by Context.Consumer)
    in Connect(Page) (created by NotificationsPage)
    in NotificationsPage (created by Context.Consumer)
    in Connect(NotificationsPage) (created by Context.Consumer)
    in Route (created by PrivateRoute)
    in PrivateRoute (created by AppRouter)
    in Switch (created by AppRouter)
    in Suspense (created by AppRouter)
    in AppRouter (created by Context.Consumer)
    in withRouter(AppRouter) (created by Context.Consumer)
    in Connect(withRouter(AppRouter)) (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in withRouter(App) (created by Context.Consumer)
    in Connect(withRouter(App)) (created by HotExportedConnect(withRouter(App)))
    in AppContainer (created by HotExportedConnect(withRouter(App)))
    in HotExportedConnect(withRouter(App)) (created by AppWrapper)
    in ErrorBoundary (created by Context.Consumer)
    in withRouter(ErrorBoundary) (created by AppWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext) (created by AppWrapper)
    in PersistGate (created by AppWrapper)
    in Provider (created by AppWrapper)
    in AppWrapper
    ```
    </details>

- [ ] Channel Page -- Reach problem, need upgrade?
     <details>
      <summary>Toggle...</summary>

   ```
    Warning: Passing `observe` as the second argument to `useRect` is deprecated and will be removed in a future version of Reach UI. Instead, you can pass an object of options with an `observe` property as the second argument (`useRect(ref, { observe })`).
    See https://reach.tech/rect#userect-observe 
    at Tab (webpack-internal:///../ui/component/common/tabs.jsx:181:26)
    at div
    at TabList (webpack-internal:///../node_modules/@reach/tabs/es/index.js:125:24)
    at TabList (webpack-internal:///../ui/component/common/tabs.jsx:166:25)
    at div
    at Tabs (webpack-internal:///../node_modules/@reach/tabs/es/index.js:48:23)
    at Tabs (webpack-internal:///../ui/component/common/tabs.jsx:138:73)
    at main
    at div
    at Page (webpack-internal:///../ui/component/page/view.jsx:74:24)
    at Connect(Page) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ChannelPage (webpack-internal:///../ui/page/channel/view.jsx:118:19)
    at Connect(ChannelPage) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Suspense
    at ShowPage (webpack-internal:///../ui/page/show/view.jsx:45:30)
    at Connect(ShowPage) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at C (webpack-internal:///../node_modules/react-router/esm/react-router.js:693:37)
    at Route (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Switch (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Suspense
    at AppRouter (webpack-internal:///../ui/component/router/view.jsx:260:29)
    at C (webpack-internal:///../node_modules/react-router/esm/react-router.js:693:37)
    at Connect(withRouter(AppRouter)) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at div
    at App (webpack-internal:///../ui/component/app/view.jsx:151:21)
    at C (webpack-internal:///../node_modules/react-router/esm/react-router.js:693:37)
    at Connect(withRouter(App)) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at AppContainer (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at HotExportedConnect(withRouter(App)) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at C (webpack-internal:///../node_modules/react-router/esm/react-router.js:693:37)
    at Router (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ConnectedRouter (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ConnectedRouterWithContext (webpack-internal:///../node_modules/connected-react-router/esm/ConnectedRouter.js:258:25)
    at Connect(ConnectedRouterWithContext) (eval at ES6ProxyComponentFactory (webpack-
   ```
    </details>

- [ ] Opening a Modal
     <details>
      <summary>Toggle...</summary>

    ```
    Warning: react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen readers don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`. 
    at ModalPortal (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Modal (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Modal (webpack-internal:///../ui/modal/modal.jsx:175:24)
    at ModalSendTip (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Connect (webpack-internal:///../node_modules/react-redux/es/components/connectAdvanced.js:155:37)
    at Suspense
    at ModalRouter (webpack-internal:///../ui/modal/modalRouter/view.jsx:147:21)
    at C (webpack-internal:///../node_modules/react-router/esm/react-router.js:693:37)
    at Connect (webpack-internal:///../node_modules/react-redux/es/components/connectAdvanced.js:155:37)
    at Suspense
    at div
    at App (webpack-internal:///../ui/component/app/view.jsx:151:21)
    at C (webpack-internal:///../node_modules/react-router/esm/react-router.js:693:37)
    at Connect(withRouter(App)) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at AppContainer (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at HotExportedConnect(withRouter(App)) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ErrorBoundary (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at C (webpack-internal:///../node_modules/react-router/esm/react-router.js:693:37)
    at Router (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ConnectedRouter (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at ConnectedRouterWithContext (webpack-internal:///../node_modules/connected-react-router/esm/ConnectedRouter.js:258:25)
    at Connect(ConnectedRouterWithContext) (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at PersistGate (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at Provider (eval at ES6ProxyComponentFactory (webpack-internal:///../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at AppWrapper (webpack-internal:///../ui/index.jsx:191:73)
    overrideMethod @ react_devtools_backend.js:2850
    ```
    </details>

**Comment by infinite-persistence** [comment]
https://github.com/OdyseeTeam/odysee-frontend/pull/2117 addresses "Opening a Modal"
