### ISSUE TITLE
Blank content listings in app.

### ISSUE THREAD

**Issue by BloodyMess** [lbryio/lbry-desktop#7242]
**Bug**
No content is displayed in the tiles where they are normally listed. I've noticed that the desktop app has been getting slower and slower at showing content when starting up for a week or so. Now there isn't any content showing up at all in the top section. Some content is eventually listed after a long delay in the "CableTube Escape Artists" section, but it cannot be viewed or downloaded. I have left the desktop app running for hours, but listings and accessibility never improves beyond this anymore.

**To Reproduce**
1. Launch LBRY desktop
2. Wait
3. See the error: Lots of blank tiles where there should be content listed.

**Expected behavior**
I expect the content listings to be populated with entries instead of blank placeholders.

**Screenshots**
![Screenshot from 2021-10-10 15-52-01](https://user-images.githubusercontent.com/12903370/136715488-20ceb294-7a79-4d28-85ff-41c164083392.png)

**System Configuration**

LBRY Daemon: 0.99.0
LBRY App: 0.51.2
OS: elementaryOS 5.1.7 Hera (Linux-5.4.0-87-x86_64)

**Additional context**
Here is a sample of the log file. There are more entries like these added every ten seconds or so:
```
2021-10-10 14:59:17,059 WARNING  lbry.wallet.network:83: Wallet server (spv14.lbry.com:50001) returned an error. Code: -32000 Message: query timed out
2021-10-10 14:59:17,060 ERROR    lbry.extras.daemon.daemon:701: error handling api request
Traceback (most recent call last):
  File "lbry/extras/daemon/daemon.py", line 693, in _process_rpc_call
  File "lbry/extras/daemon/daemon.py", line 2492, in jsonrpc_claim_search
  File "lbry/wallet/ledger.py", line 889, in claim_search
  File "lbry/wallet/ledger.py", line 772, in _inflate_outputs
  File "lbry/wallet/network.py", line 84, in send_request
  File "lbry/wallet/network.py", line 74, in send_request
  File "lbry/wallet/rpc/session.py", line 483, in send_request
lbry.wallet.rpc.jsonrpc.RPCError: (-32000, 'query timed out')
```

**Comment by BloodyMess** [comment]
That did it!

Thank you!
