### ISSUE TITLE
Error starting up, You can try refreshing to fix it. ; Failed to bind TCP 0.0.0.0:4444 ; AttributeError: 'NoneType' object has no attribute 'stop'

### ISSUE THREAD

**Issue by slrslr** [lbryio/lbry-desktop#7718]
Hello, today I have downloaded LBRY_0.53.6.AppImage made executable and ran with errors:

```
Starting SDK
[2525400:1105/202731.005946:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Daemon: 2022-11-05 20:27:32,498 INFO     lbry.extras.daemon.daemon:489: Starting LBRYNet Daemon

Daemon: 2022-11-05 20:27:32,498 INFO     lbry.extras.daemon.daemon:491: Platform: {
  "processor": "",
  "python_version": "3.7.14",
  "platform": "Linux-5.15.0-0.bpo.3-amd64-x86_64-with-debian-11.5",
  "os_release": "5.15.0-0.bpo.3-amd64",
  "os_system": "Linux",
  "lbrynet_version": "0.111.0",
  "version": "0.111.0",
  "build": "release",
  "distro": {
    "id": "debian",
    "version": "11",
    "version_parts": {
      "major": "11",
      "minor": "",
      "build_number": ""
    },
    "like": "",
    "codename": "bullseye"
  },
  "desktop": "KDE"
}

Daemon: 2022-11-05 20:27:37,368 ERROR    lbry.blob_exchange.server:176: Failed to bind TCP 0.0.0.0:4444
```

GUI shows:

> Error starting up
> You can try refreshing to fix it. If you still have issues, your anti-virus software or firewall may be preventing startup.
> 
> Reach out to hello@lbry.com for help, or check out [this link](https://lbry.com/faq/startup-troubleshooting).
> 
> [Refresh]
> 

After Refresh:

```
Daemon: 2022-11-05 20:43:26,142 ERROR    lbry.extras.daemon.component:74: Error stopping WalletComponent
Traceback (most recent call last):
  File "lbry/extras/daemon/component.py", line 67, in _stop
  File "lbry/extras/daemon/components.py", line 174, in stop
AttributeError: 'NoneType' object has no attribute 'stop'

Daemon: Task exception was never retrieved
future: <Task finished coro=<Component._stop() done, defined at lbry/extras/daemon/component.py:65> exception=AttributeError("'NoneType' object has no attribute 'stop'")>
Traceback (most recent call last):
  File "lbry/extras/daemon/component.py", line 75, in _stop
  File "lbry/extras/daemon/component.py", line 67, in _stop
  File "lbry/extras/daemon/components.py", line 174, in stop
AttributeError: 'NoneType' object has no attribute 'stop'

Daemon: 2022-11-05 20:43:26,144 INFO     lbry.extras.daemon.exchange_rate_manager:220: Stopping exchange rate manager

Daemon: 2022-11-05 20:43:26,145 INFO     lbry.extras.daemon.components:673: Removing upnp redirects: {'TCP': 4444, 'UDP': 4444}

...

Daemon: 2022-11-05 20:43:26,172 INFO     lbry.extras.daemon.daemon:571: finished shutting down

Daemon: Task was destroyed but it is pending!
task: <Task pending coro=<Event.wait() running at asyncio/locks.py:293> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8db038b610>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Component._setup() done, defined at lbry/extras/daemon/component.py:53> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8db0390310>()]>>

Daemon: Task exception was never retrieved
future: <Task finished coro=<BlobServer.start_server.<locals>._start_server() done, defined at lbry/blob_exchange/server.py:170> exception=OSError(98, "error while attempting to bind on address ('0.0.0.0', 4444): address already in use")>
Traceback (most recent call last):
  File "lbry/blob_exchange/server.py", line 181, in _start_server
  File "asyncio/base_events.py", line 1389, in create_server
  
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 4444): address already in use
```

My feedback regarding this is that the software should report last mentioned log line (OSError: [Errno 98]) before i clicked Refresh IMO, it should be near the first related line that mention "Failed to bind" issue.

When ran "`sudo ./LBRY_0.53.6.AppImage --no-sandbox`" result is same, only it adds some more lines at the beginning:

```
[2556691:1105/205057.896201:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
(lbry:2556691): libayatana-appindicator-WARNING **: 20:50:57.974: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”
(lbry:2556691): LIBDBUSMENU-GLIB-WARNING **: 20:50:57.975: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
```

`sudo netstat -tulnp|grep 4444` shown that I2Pd (third party service) is using 4444 port. So i have set other port in /etc/i2pd/i2pd.conf and "sudo systemctl restart i2pd".

Now it started. But still if you can consider what i have written and exceptions shown.

**Comment by jessopb** [comment]
Thank you for the feedback. Splash page could definitely be more explicit with errors.
